// Standardized action names for SystemLog
module.exports = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USERDATA_CREATE: 'USERDATA_CREATE',
  USERDATA_UPDATE: 'USERDATA_UPDATE',
  USERDATA_DELETE: 'USERDATA_DELETE',
  BACKUP_START: 'BACKUP_START',
  BACKUP_COMPLETE: 'BACKUP_COMPLETE',
  BACKUP_FAIL: 'BACKUP_FAIL',
  RESTORE_REQUEST: 'RESTORE_REQUEST',
  RESTORE_APPROVE: 'RESTORE_APPROVE',
  RESTORE_EXECUTE: 'RESTORE_EXECUTE',
  RESTORE_VERIFY: 'RESTORE_VERIFY',
};
